2020-03-26 02:34:08,973 WARNING Had an exception while running the client!
2020-03-26 02:34:08,974 WARNING Traceback (most recent call last):
  File "c:/Users/ram/Desktop/temp/fics/test/t6/UsageResearch/Client/client.py", line 114, in <module>
    main()
  File "c:/Users/ram/Desktop/temp/fics/test/t6/UsageResearch/Client/client.py", line 98, in main
    with open(USERID_FILE) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Florida\\FICS\\src\\newRepo\\FIRMA\\FIRMA kernel extractor\\UserStudy\\UsageResearch\\Client\\UserId.txt'

2020-03-26 02:34:57,753 WARNING Had an exception while running the client!
2020-03-26 02:34:57,754 WARNING Traceback (most recent call last):
  File "client.pyw", line 113, in <module>
    main()
  File "client.pyw", line 98, in main
    with open(USERID_FILE) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Florida\\FICS\\src\\newRepo\\FIRMA\\FIRMA kernel extractor\\UserStudy\\UsageResearch\\Client\\UserId.txt'

